package edu.ifce.folhapagamento.controllers;

import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.mysql.cj.result.Field;

import edu.ifce.folhapagamento.domain.Colaborador;
import edu.ifce.folhapagamento.repositories.ColaboradorRepository;





	@Controller    // This means that this class is a Controller
	@RequestMapping(path="/folhapagamento") // This means URL's start with /demo (after Application path)
	public class ColaboradorController {
		private final String ITEM_URI = "folhapagamento/";
	   @Autowired // This means to get the bean called userRepository
		           // Which is auto-generated by Spring, we will use it to handle the data
	
	   private ColaboradorRepository colaboradorRepository;
	   @GetMapping(path="/colaboradores/add") // Map ONLY GET Requests
	   
		public  @ResponseBody String addNewColaborador (
				@RequestParam String nome, 
				@RequestParam String salarioAtual,
				@RequestParam String cpf,
				@RequestParam String endereco,
				@RequestParam String telefone,
				@RequestParam String bairro,
				@RequestParam String cep) {
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request
		  
			Colaborador colaborador = new Colaborador();
			colaborador.setNome(nome);
			colaborador.setSalarioAtual(Float.parseFloat(salarioAtual));
			colaborador.setCpf(cpf);
			colaborador.setEndereco(endereco);
			colaborador.setTelefone(telefone);
			colaborador.setBairro(bairro);
			colaborador.setCep(cep);
			colaboradorRepository.save(colaborador);
			return "Dados Salvos Com Sucesso!";
		}
	  
	   
		@GetMapping(path="/colaboradores/list/all")
		public @ResponseBody Iterable<Colaborador> getAllColaboradores() {
			// This returns a JSON or XML with the users
			return colaboradorRepository.findAll();
		}
		
		@GetMapping("/colaboradores/list/{id}")
		public  @ResponseBody Colaborador viewColaborador(@PathVariable("id") Integer id, Model model) {
			Colaborador colaborador = new Colaborador();
			try {
				colaborador = colaboradorRepository.findById(id).get();				
			}catch (Exception e) {
				
			}
			return colaborador;
		}
					
		@RequestMapping(path="/colaboradores/delete/{id}")
	    public String removeColaborador(@PathVariable("id") Integer id){
			
			colaboradorRepository.deleteById(id);
	        return "redirect:/folhapagamento/colaboradores/list";
	        //return "Dados Excluidos Com Sucesso!";
		
		}
		
	    @GetMapping("/colaboradores/edit/{id}")
	    @ResponseBody
	    public String editColaborador(@PathVariable("id") Integer id, 
	    @RequestParam(value="nome", required=false)  String nome,
	    @RequestParam(value="salarioAtual", required=false)  String salarioAtual,
	    @RequestParam(value="cpf", required=false)  String cpf,
	    @RequestParam(value="endereco", required=false)  String endereco,
	    @RequestParam(value="telefone", required=false) String telefone, 
	    @RequestParam(value="bairro", required=false)String bairro, 
	    @RequestParam(value="cep", required=false)String cep){
	    	 	    		 	   		 
	    		
	    		 try {	
    			 Colaborador colaborador = colaboradorRepository.findById(id).get();
    		     if (!(nome == null)) colaborador.setNome(nome);
	    		 if (!(salarioAtual == null)) colaborador.setSalarioAtual(Float.parseFloat(salarioAtual));
	    		 if (!(cpf == null)) colaborador.setCpf(cpf);
	    		 if (!(endereco == null)) colaborador.setEndereco(endereco);
	    		 if (!(telefone == null)) colaborador.setTelefone(telefone);
	    		 if (!(bairro == null)) colaborador.setBairro(bairro);
	    		 if (!(cep == null)) colaborador.setCep(cep);
	    	     colaboradorRepository.save(colaborador);	    		 
	    	    }
	    	    catch (Exception ex) {
	    	      return "Erro ao Atualizar o Registro: " + ex.toString();
	    	    }
	    	return "Dados atualizados com sucesso";
	    }
	}

		
	
	


